### ISSUE TITLE
illegible characters in .txt file

### ISSUE THREAD

**Issue by billredmann** [SMPTE/ag-30#1]
In the bsd-3-clause.txt file, surrounding the phrase "as is" appear to be some weird characters that do not render correctly in a .txt file viewer.

Probably these weird characters are supposed to represent quotes of some kind or is intended to show the phrase in italics.  Perhaps use plain quotes?  Or some other convention that doesn't result in illegible characters.

**Comment by palemieux** [comment]
> Probably these weird characters are supposed to represent quotes of some kind or is intended to show the phrase in italics. 

They are LEFT/RIGHT DOUBLE QUOTATION MARK (`“”`). Will replace with QUOTATION MARK (`"`).

**Comment by palemieux** [comment]
@billredmann Please review https://github.com/SMPTE/ag-30/pull/2
